// The router API does NOT return a device vendor/brand — only a hostname
// (`name`) and MAC. Brand is derived here from the MAC's OUI (first 3 octets)
// against the IEEE MA-L registry (public/oui.json, ~40k entries, generated by
// scripts/build-oui.mjs). The registry is served as a static asset and fetched
// lazily (see ensureOuiLoaded) so its ~1.2 MB stays out of the JS bundle.
// Modern phones/laptops use a randomized ("locally administered") MAC that maps
// to no real vendor — we detect that bit and report "Private" rather than a
// wrong brand.

let ouiRegistry: Record<string, string> | null = null;
let ouiLoad: Promise<void> | null = null;
const registryListeners = new Set<() => void>();

export function isOuiRegistryLoaded(): boolean {
  return ouiRegistry !== null;
}

export function subscribeToOuiRegistry(listener: () => void): () => void {
  registryListeners.add(listener);
  return () => registryListeners.delete(listener);
}

/** Fetches the IEEE OUI registry once from the static asset. */
export function ensureOuiLoaded(): Promise<void> {
  return (ouiLoad ??= fetch(`${import.meta.env.BASE_URL}oui.json`)
    .then((response) => response.json())
    .then((registry: Record<string, string>) => {
      ouiRegistry = registry;
      for (const listener of registryListeners) listener();
    })
    .catch(() => {
      // Leave the registry unloaded; vendorForMac falls back to private-MAC
      // detection only. Reset so a later open can retry.
      ouiLoad = null;
    }));
}

/** First 3 octets as 6 lowercase hex chars, separators stripped. */
function ouiKey(macAddress: string): string {
  return macAddress
    .replace(/[^0-9a-fA-F]/g, "")
    .slice(0, 6)
    .toLowerCase();
}

/** True when the MAC is a randomized/locally-administered address (2nd nibble is 2,6,A,E). */
export function isPrivateMac(macAddress: string | undefined): boolean {
  if (!macAddress) return false;
  const secondNibble = macAddress.replace(/[^0-9a-fA-F]/g, "")[1]?.toLowerCase();
  return (
    secondNibble === "2" || secondNibble === "6" || secondNibble === "a" || secondNibble === "e"
  );
}

/** Best-effort brand for a device: real OUI vendor, else "Private" for a
    randomized MAC, else undefined (unknown). Never guesses a brand for a
    randomized MAC. Resolves against the full registry once ensureOuiLoaded()
    has completed; before then only randomized MACs are classified. */
export function vendorForMac(macAddress: string | undefined): string | undefined {
  if (!macAddress) return undefined;
  const vendor = ouiRegistry?.[ouiKey(macAddress)];
  if (vendor) return vendor;
  if (isPrivateMac(macAddress)) return "Private";
  return undefined;
}
